"""schema inicial E-Ponto

Revision ID: 70275fbd7283
Revises: 
Create Date: 2026-05-26 20:03:00.844113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70275fbd7283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index('idx_city_name_state_country', ['name', 'state', 'country'], unique=False)

    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_levels_name'), ['name'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('facebook_id', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=15), nullable=True),
    sa.Column('pis_nis', sa.String(length=15), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_cpf'), ['cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_pis_nis'), ['pis_nis'], unique=False)

    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road', sa.String(length=100), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.String(length=15), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_user_id'), ['user_id'], unique=False)

    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('corporate_name', sa.String(length=120), nullable=False),
    sa.Column('trade_name', sa.String(length=120), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cei_caepf', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=60), nullable=True),
    sa.Column('bairro', sa.String(length=60), nullable=True),
    sa.Column('cidade', sa.String(length=60), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_cnpj'), ['cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_businesses_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_trade_name'), ['trade_name'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('tabela', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('dados_antes', sa.Text(), nullable=True),
    sa.Column('dados_depois', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('banco_horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('minutos_positivos', sa.Integer(), nullable=False),
    sa.Column('minutos_negativos', sa.Integer(), nullable=False),
    sa.Column('saldo_minutos', sa.Integer(), nullable=False),
    sa.Column('fechado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'empresa_id', 'periodo', name='uq_banco_horas_user_empresa_periodo')
    )
    with op.batch_alter_table('banco_horas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banco_horas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_banco_horas_user_id'), ['user_id'], unique=False)

    op.create_table('jornadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('carga_horaria_semanal', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('horario_entrada', sa.Time(), nullable=True),
    sa.Column('horario_saida', sa.Time(), nullable=True),
    sa.Column('intervalo_minutos', sa.Integer(), nullable=False),
    sa.Column('tolerancia_minutos', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jornadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jornadas_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('locais_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('logradouro', sa.String(length=120), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=60), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('raio_metros', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locais_trabalho', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locais_trabalho_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('nsr_sequencias',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ultimo_nsr', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('empresa_id')
    )
    op.create_table('roles_has_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'business_id', name='uq_user_role_business')
    )
    with op.batch_alter_table('roles_has_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_has_users_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_has_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_has_users_user_id'), ['user_id'], unique=False)

    op.create_table('escalas_funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('jornada_id', sa.Integer(), nullable=True),
    sa.Column('local_trabalho_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['jornada_id'], ['jornadas.id'], ),
    sa.ForeignKeyConstraint(['local_trabalho_id'], ['locais_trabalho.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalas_funcionarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalas_funcionarios_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalas_funcionarios_user_id'), ['user_id'], unique=False)

    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nsr', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA_ALMOCO', 'RETORNO_ALMOCO', 'SAIDA', 'INCLUSAO', 'ALTERACAO', name='tiporegistro'), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('precisao_metros', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('suspeito_geo', sa.Boolean(), nullable=False),
    sa.Column('local_trabalho_id', sa.Integer(), nullable=True),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.Column('hash_registro', sa.String(length=64), nullable=False),
    sa.Column('hash_anterior', sa.String(length=64), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('aprovador_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aprovador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['local_trabalho_id'], ['locais_trabalho.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nsr', name='uq_empresa_nsr')
    )
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_timestamp_utc'), ['timestamp_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_user_id'), ['user_id'], unique=False)

    op.create_table('retificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('novo_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADA', 'REJEITADA', name='statusretificacao'), nullable=False),
    sa.Column('aprovador_id', sa.Integer(), nullable=True),
    sa.Column('observacao_aprovador', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('aprovado_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprovador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['registro_id'], ['registros.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retificacoes_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retificacoes_registro_id'), ['registro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retificacoes_solicitante_id'), ['solicitante_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retificacoes_solicitante_id'))
        batch_op.drop_index(batch_op.f('ix_retificacoes_registro_id'))
        batch_op.drop_index(batch_op.f('ix_retificacoes_empresa_id'))

    op.drop_table('retificacoes')
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_user_id'))
        batch_op.drop_index(batch_op.f('ix_registros_timestamp_utc'))
        batch_op.drop_index(batch_op.f('ix_registros_empresa_id'))

    op.drop_table('registros')
    with op.batch_alter_table('escalas_funcionarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalas_funcionarios_user_id'))
        batch_op.drop_index(batch_op.f('ix_escalas_funcionarios_empresa_id'))

    op.drop_table('escalas_funcionarios')
    with op.batch_alter_table('roles_has_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_has_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_roles_has_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_roles_has_users_business_id'))

    op.drop_table('roles_has_users')
    op.drop_table('nsr_sequencias')
    with op.batch_alter_table('locais_trabalho', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locais_trabalho_empresa_id'))

    op.drop_table('locais_trabalho')
    with op.batch_alter_table('jornadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jornadas_empresa_id'))

    op.drop_table('jornadas')
    with op.batch_alter_table('banco_horas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banco_horas_user_id'))
        batch_op.drop_index(batch_op.f('ix_banco_horas_empresa_id'))

    op.drop_table('banco_horas')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_empresa_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_trade_name'))
        batch_op.drop_index(batch_op.f('ix_businesses_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_is_active'))
        batch_op.drop_index(batch_op.f('ix_businesses_cnpj'))

    op.drop_table('businesses')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_user_id'))

    op.drop_table('address')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_pis_nis'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_cpf'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_levels_name'))

    op.drop_table('levels')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index('idx_city_name_state_country')

    op.drop_table('cities')
    # ### end Alembic commands ###
